# Generated by Django 3.0.6 on 2020-08-02 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
