# Generated by Django 3.0.6 on 2020-08-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0002_auto_20200802_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Created_On',
        ),
    ]
