# Generated by Django 3.0.6 on 2020-08-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders_id',
            old_name='Order_Id',
            new_name='Order_ID',
        ),
        migrations.AlterField(
            model_name='orders_id',
            name='Refund_Amount',
            field=models.IntegerField(default=0),
        ),
    ]
