# Generated by Django 3.0.6 on 2020-08-21 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200821_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordered_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=130)),
                ('Product_Price', models.PositiveSmallIntegerField()),
                ('Product_Category', models.CharField(max_length=80)),
                ('Product_Id', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='orders_id',
            name='Refund_Amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders_id',
            name='Total_Amount',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveSmallIntegerField()),
                ('Seller_Id', models.PositiveSmallIntegerField()),
                ('Address', models.CharField(max_length=1000)),
                ('OTP', models.PositiveSmallIntegerField()),
                ('Total_Amount', models.PositiveSmallIntegerField()),
                ('Date_Time', models.DateTimeField(auto_now_add=True)),
                ('Delivery_Status', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('Orders_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders_Id')),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.Ordered_Product')),
            ],
        ),
        migrations.AddField(
            model_name='ordered_product',
            name='Orders_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders_Id'),
        ),
    ]
