# Generated by Django 3.0.6 on 2020-08-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_id_txn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_id',
            name='TXN_ID',
            field=models.BigIntegerField(default=-1),
        ),
    ]
