# Generated by Django 3.0.6 on 2020-08-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200821_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders_id',
            old_name='Status',
            new_name='Payment_Status',
        ),
    ]
