# Generated by Django 3.0.6 on 2020-08-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200821_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Address',
        ),
        migrations.AddField(
            model_name='orders_id',
            name='Address',
            field=models.CharField(default='mine', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders_id',
            name='Mobile',
            field=models.BigIntegerField(default=9999999999),
        ),
    ]
