# Generated by Django 3.0.6 on 2020-08-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200822_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_id',
            name='TXN_ID',
            field=models.CharField(default=-1, max_length=200),
        ),
        migrations.AlterField(
            model_name='orders_id',
            name='Total_Amount',
            field=models.FloatField(),
        ),
    ]
