# Generated by Django 3.0.6 on 2020-08-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200823_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Orders_Id',
            new_name='Orders_ID',
        ),
    ]
